import type { EnviatodoPackage, EnviatodoProvider, EnviatodoOrderStatus } from "./types";

export const ENVIATODO_PROVIDERS: EnviatodoProvider[] = [
  { provider_id: 1, name: "FEDEX", provider_service_id: 1, transport: "Terrestre" },
  { provider_id: 1, name: "FEDEX", provider_service_id: 2, transport: "Aereo" },
  { provider_id: 4, name: "PAQUETEXPRESS", provider_service_id: 5, transport: "Terrestre" },
  { provider_id: 5, name: "DHL", provider_service_id: 6, transport: "Aereo" },
  { provider_id: 5, name: "DHL", provider_service_id: 16, transport: "Terrestre" },
  { provider_id: 8, name: "SENDEX", provider_service_id: 9, transport: "Terrestre" },
  { provider_id: 9, name: "ESTAFETA", provider_service_id: 11, transport: "Aereo" },
  { provider_id: 9, name: "ESTAFETA", provider_service_id: 12, transport: "Terrestre" },
  { provider_id: 11, name: "BIGSMART", provider_service_id: 18, transport: "Local Terrestre" },
  { provider_id: 11, name: "BIGSMART", provider_service_id: 19, transport: "Foraneo 1" },
  { provider_id: 11, name: "BIGSMART", provider_service_id: 20, transport: "Foraneo 2" },
  { provider_id: 12, name: "GRUPO AMPM", provider_service_id: 21, transport: "Estandar Terrestre" },
  { provider_id: 14, name: "AFIMEX", provider_service_id: 23, transport: "Estandar Terrestre" },
  { provider_id: 15, name: "IMILE", provider_service_id: 24, transport: "Estandar Terrestre" },
  { provider_id: 16, name: "UBER", provider_service_id: 25, transport: "Envio Express 2 ruedas" },
  { provider_id: 16, name: "UBER", provider_service_id: 26, transport: "Envio Express 4 ruedas" },
];

export const MEXICO_STATE_CODES: Record<string, string> = {
  AS: "Aguascalientes",
  BC: "Baja California",
  BS: "Baja California Sur",
  CC: "Campeche",
  CL: "Coahuila",
  CM: "Colima",
  CS: "Chiapas",
  CH: "Chihuahua",
  DF: "Ciudad de Mexico",
  DG: "Durango",
  GT: "Guanajuato",
  GR: "Guerrero",
  HG: "Hidalgo",
  JC: "Jalisco",
  MC: "Mexico",
  MN: "Michoacan",
  MS: "Morelos",
  NT: "Nayarit",
  NL: "Nuevo Leon",
  OC: "Oaxaca",
  PL: "Puebla",
  QO: "Queretaro",
  QR: "Quintana Roo",
  SP: "San Luis Potosi",
  SL: "Sinaloa",
  SR: "Sonora",
  TC: "Tabasco",
  TS: "Tamaulipas",
  TL: "Tlaxcala",
  VZ: "Veracruz",
  YN: "Yucatan",
  ZS: "Zacatecas",
};

export const ENVIATODO_ORDER_STATUSES: Record<number, EnviatodoOrderStatus> = {
  41: { name: "Guia generada", type: "ORDER" },
  42: { name: "Guia en transito", type: "ORDER" },
  43: { name: "Guia cancelada", type: "ORDER" },
  44: { name: "Guia entregada", type: "ORDER" },
  59: { name: "Recoleccion", type: "ORDER" },
  60: { name: "Recoleccion pendiente", type: "PICKUP" },
  61: { name: "Recoleccion generada", type: "PICKUP" },
  62: { name: "Recoleccion cancelada", type: "PICKUP" },
  68: { name: "Guia en devolucion", type: "ORDER" },
  69: { name: "Incidencia en guia", type: "ORDER" },
  71: { name: "Recoleccion Reprogramada", type: "PICKUP" },
};

export const ENVIATODO_PACKAGE_PRESETS = {
  PLAYERA: {
    height: 4,
    width: 28,
    length: 35,
    weight: 1,
    real_weight: "1.00",
    volumetric_weight: "1",
    bill_weight: "1",
    package_content: "PLAYERAS",
    product_type: "53100000",
    unit_type: "XBX",
    amount_pkg: "300",
    product_quantity: "1",
  },
  SUDADERA: {
    height: 8,
    width: 30,
    length: 40,
    weight: 2,
    real_weight: "2.00",
    volumetric_weight: "2",
    bill_weight: "2",
    package_content: "SUDADERA",
    product_type: "53100000",
    unit_type: "XBX",
    amount_pkg: "600",
    product_quantity: "1",
  },
} satisfies Record<string, EnviatodoPackage>;
